---
title: "HW02"
author: "Eleanor King, elejking"
date: "r Sys.Date()"
output: pdf_document
---

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)


## Question 1 (4 points)

The [Monty Hall Problem](https://en.wikipedia.org/wiki/Monty_Hall_problem) is a classic statistical puzzle. Borrowing from a famous article on the subject:

> Suppose you're on a game show, and you're given the choice of three doors: Behind one door is a car; behind the others, goats. You pick a door, say No. 1, and the host, who knows what's behind the doors, opens another door, say No. 3, which has a goat. He then says to you, "Do you want to pick door No. 2?" Is it to your advantage to switch your choice?

Along with this basic framework, assume:

* The host must always open a door that was not selected by the contestant.
* The host must always open a door to reveal a goat and never the car.
* The host must always offer the chance to switch between the door chosen originally and the closed door remaining.

## Question 1.a (1 point)

Write up the Monty Hall problem in terms of random variables and verify the choice of switching has a 2/3 probability of winning the car.

{r}
monty_hall <- function(n = 10000) {
 cars <- sample(1:3, n, replace = TRUE)
 original_choices <- sample(1:3, n, replace = TRUE)
 switch_wins <- numeric(n)
 
 for (i in 1:n) {
   car <- cars[i]
   original_choice <- original_choices[i]
   
   reveal_poss <- setdiff(1:3, c(original_choice, car))
   reveal_real <- sample(reveal_poss, 1)

   remaining_door <- setdiff(1:3, c(original_choice, reveal_real))
   
   if(length(remaining_door) == 1 && car == remaining_door) {
     switch_wins[i] <- 1
   } else {
     switch_wins[i] <- 0
   }
 }
 
 mean(switch_wins)
}
 
monty_hall()



## Question 1.b (1 point)

Here are 10,000 replications of selecting a random door to put the car behind.

{r}
cars <- sample(1:3, 10000, replace = TRUE)


For each choice of door, run the Monty Hall problem 10,000 times and calculate the proportion of times the contestant wins the car when switching doors. 

Hints:

* when calculating the final probability of winning the car, you can use the mean function to calculate the proportion of times the contestant wins the car when switching doors. For example, here's the simulated probablility of randomly selecting the car on the initial guess:

{r}
mean(sample(1:3, 10000, replace = TRUE) == cars)


* the if_else function can be useful to select between values based on a condition. Here's an example:
{r}
x <- 1:10
# for the values 5 to 10, double those values, otherwise return the original value
if_else(x < 5, x, 2*x)


{r}



## Question 1.c (2 point)

Consider a variant of the Monty Hall problem where if the user picks the car in the first round, with probability $p$, the host will immediately reveal that the car is behind the door the user selected and with probability $1-p$ will open another door with a goat. 

Update your simulation to calculate the probability of winning the car when switching doors in this variant of the Monty Hall problem with $p = 0.25$.

Here is how you can sample two options with specific probability:


{r}
sample(c(TRUE, FALSE), 10, replace = TRUE, prob = c(0.25, 0.75))


{r}
# Question 1.c


## Question 2 (5 points)

Let $U_1$ and $U_2$ be two independent random variables that are uniformly distributed on the interval $[0, 1]$. Let $X = U_1 + U_2$.

## Question 2.a (2 points)

Find the CDF of $X$.

For \(0 \leq 1:
$F_X$(x) = P($U_1 + U_1\leq x$)
$F_X$(x) = $\int_0^x\int_0^{x-u_1}$1$du_2du_1$ = $\int_0^x$(x-$u_1$)$du_1$ = $\frac{x^2}{2}$

For 1 $\leq$ 2:
$F_X$(x) = P($U_1 + U_1 \leq x$) = 1 - P($U_1$ + $U_1$ > x)
P($U_1 + U_2 > x$) = $\int_0^1\int_{x-u_1}^{1}$1$du_2du_1$ = $\int_0^{x-1}$(1 - (x - $u_1$))$du_1$ + $\int_{x-1}^1$(1 - (x - $u_1$))$du_1$
$F_X$(x) = 1 - $\frac{(2-x)^2}{2}$
{r}



## Question 2.b (1 point)

Using the runif function, generate 10,000 draws of $U_1$. Then generate 10,000 draws of $U_2$. Calculate the values of $X$ and $Y$ for each pair of draws. Plot results using plot(ecdf(RESULT)), where RESULT is the 10,000 values of $X$ or $Y$.

{r}
set.seed(123)
U_1 <- runif(10000)
U_2 <- runif(10000)

X <- U_1 + U_2

plot(ecdf(X), main="ECDF of X = U_1 + U_2", ylab = "ECDF", col = "blue")


## Question 2.c (1 point)

Take the derivative of the CDF from 2.a to get the PDF of $X$.

{r}


## Question 2.d (1 point)

Find the mean and variance of $X$ analytically. Verify your results by comparing it to the mean and variance you would calculate from the 10,000 draws of $X$.

{r}
U_1 <- runif(10000)
U_2 <- runif(10000)
n <- 10000

X <- U_1 + U_2

mean_X <- mean(X)
var_X <- var(X)

print(mean_X)
print(var_X)


## Question 3 (6 points)

Consider a variation on the uniform distribution. Let $X$ be a random variable with the following PDF:

$$f(x) = \frac{1}{\theta} \text{ for } 0 \leq x \leq \theta$$
Suppose that $X_1, X_2, \ldots, X_n$ are independent and identically distributed random variables with this PDF. 

While the output is suppressed, the next chunk defines a vector x that contains a sample of 1000 random variables from this distribution.

{r echo = FALSE}
x <- c(1.12697961321101, 5.45682713272981, 4.77657136018388, 3.29002340068109, 
0.123430412728339, 3.67342025274411, 3.09185637696646, 2.74907605885528, 
3.16958140116185, 0.384938379516825, 2.36123094917275, 4.07640412915498, 
1.78495561610907, 1.25764413527213, 5.60947886947542, 0.0126053700223565, 
4.41430675797164, 4.84060383844189, 1.24521914822981, 1.90370732848532, 
5.810466427356, 3.32522843871266, 1.93786504934542, 4.63398943562061, 
6.01552825421095, 5.12588410521857, 1.36064904602244, 2.20248977397569, 
0.505505799781531, 2.0563190060202, 2.28570187999867, 3.32558106374927, 
5.80539080197923, 3.39857505098917, 5.84868907020427, 4.67568347090855, 
4.14705311646685, 0.591720914002508, 1.91125275357626, 0.325846754014492, 
4.80109265935607, 6.29588045738637, 0.372188361827284, 2.05046842992306, 
5.99494197103195, 0.187485713278875, 3.47016317327507, 4.81505110464059, 
4.22606815677136, 2.14705796213821, 2.59347704704851, 1.11805056687444, 
6.65140454121865, 4.45727382018231, 5.31594905536622, 3.3794724335894, 
3.0132058202289, 5.46533799148165, 3.38160125818104, 2.27642176672816, 
1.46674798848107, 3.540737045696, 2.32057976047508, 5.02377266692929, 
4.52554866648279, 0.826874010963365, 5.16876796702854, 1.84433804941364, 
0.341210739919916, 5.05578500265256, 6.10102311591618, 0.308394633466378, 
1.55415682937019, 2.80635350849479, 3.25369870616123, 0.676532110897824, 
0.440530834021047, 0.986377988243476, 2.40550877992064, 4.60901132063009, 
3.58783146808855, 3.51444648834877, 0.0702441886533052, 0.88836455065757, 
1.16110942838714, 2.8357142386958, 3.16042181267403, 6.38796777860261, 
6.19142835447565, 2.12582111242227, 6.30340010859072, 6.18536244728602, 
5.45851767901331, 5.34416648535989, 6.44340227311477, 1.15632818010636, 
3.02678696345538, 0.747952473117039, 3.99654110288247, 4.01043012947775, 
4.94038434047252, 0.865769027266651, 1.06025679362938, 6.04496247437783, 
1.3946840565186, 0.605736815137789, 1.21942828386091, 0.714571160031483, 
2.98412644164637, 3.84875573473983, 1.3810760800261, 5.49305200926028, 
2.68877497408539, 4.31751856929623, 0.704636366572231, 2.22650151816197, 
4.09531465824693, 3.42891791881993, 1.72250884957612, 5.78684606356546, 
6.75161172868684, 2.32411211286671, 5.73226238274947, 1.33325065812096, 
0.96660763095133, 5.9171375699807, 2.37586498027667, 5.37314271298237, 
6.12551757204346, 3.80681777815334, 1.53988314047456, 5.58572568069212, 
1.67398934834637, 1.98897850466892, 0.756078415317461, 5.77074906532653, 
0.72241138597019, 3.63487372826785, 3.87636620714329, 5.73732811841182, 
1.93837146204896, 6.79698915779591, 2.52489048079588, 3.29602247406729, 
6.33666948927566, 0.326306536095217, 4.27020583651029, 3.26270736893639, 
4.51213259086944, 0.517459217924625, 1.63633574871346, 5.75775946490467, 
0.792084288783371, 0.682355909142643, 6.19825794547796, 3.49959464557469, 
0.450486317975447, 6.51783906994388, 5.74074308667332, 1.35453501692973, 
0.297030616551638, 6.59291736176237, 0.219785378780216, 3.53637353680097, 
0.743731212802231, 3.12067619455047, 1.63780390680768, 3.38012056681328, 
4.26284428709187, 2.31400591344573, 4.73890050407499, 6.83449932560325, 
3.32726274221204, 0.370099648600444, 0.731673066038638, 1.10725307348184, 
3.36346252937801, 3.00861283834092, 5.40074409265071, 4.75359230395406, 
0.935969781363383, 5.24665764160454, 0.23297036299482, 0.239593244623393, 
1.65521578723565, 2.28413247619756, 5.57497346354648, 6.38504288578406, 
0.593222447438166, 4.95668986206874, 0.428422304801643, 4.41168200853281, 
4.30845240666531, 1.57890442339703, 0.681444409303367, 6.90774779045023, 
1.43081819312647, 6.58533954736777, 1.30464532412589, 6.46071746968664, 
3.48834724677727, 2.29932176880538, 2.45203755563125, 0.202823468949646, 
2.8903602224309, 2.67002813215367, 5.30059903697111, 4.70097353728488, 
0.643326716730371, 2.46774473483674, 3.47784795402549, 6.45884416415356, 
3.01684041251428, 3.72450305777602, 0.984915557317436, 6.40193444630131, 
0.90356958238408, 2.01054743234999, 4.64848385355435, 4.59400622476824, 
4.41950396262109, 1.20761343254708, 5.66987707815133, 1.84648290975019, 
0.706447365926579, 6.57030396419577, 0.545853901654482, 6.09226962830871, 
4.53870930778794, 0.953198852017522, 5.29470497416332, 2.84079650393687, 
4.26762679032981, 3.64738941937685, 3.73185190442018, 0.577340416843072, 
1.07400434580632, 0.229474619496614, 1.75188177241944, 6.0927142938599, 
0.0456032871734351, 5.58386963326484, 1.10338776791468, 3.99364566244185, 
6.68760902713984, 6.3325223675929, 3.54000708763488, 3.97722160280682, 
5.06864384631626, 1.89153851079755, 5.30647500557825, 5.12128346646205, 
0.644276171689853, 1.03416200145148, 1.98157053650357, 5.37001011171378, 
3.9623049471993, 4.81236707232893, 1.29291959106922, 1.00850556581281, 
6.27834449592046, 5.78243359504268, 6.39282443188131, 4.37430779496208, 
1.08121858118102, 0.115499921143055, 1.68054111627862, 1.21939210197888, 
6.19966597482562, 3.21295066084713, 4.87058502435684, 4.2274148480501, 
4.25531702628359, 6.98315415089019, 0.539004951715469, 3.05146720376797, 
4.16221632878296, 2.43491389160044, 5.19837742322125, 5.10131216933951, 
4.81961886677891, 5.58633750653826, 0.974229865940288, 5.23269287589937, 
6.63070368859917, 1.30840821866877, 4.59201836609282, 3.07476310571656, 
3.76999795250595, 4.66298025171272, 5.47169631998986, 5.85750394151546, 
0.0566990578081459, 2.02141681523062, 2.49783862568438, 0.925488964188844, 
0.179403968388215, 3.64820458739996, 3.98977109137923, 2.74503700691275, 
2.69973441725597, 6.6715070058126, 5.34444673196413, 6.78258891706355, 
6.79698850098066, 4.86887064529583, 3.01467117178254, 5.54813035344705, 
0.77005364280194, 0.469049481442198, 6.3310126720462, 0.863595265429467, 
1.32755210460164, 3.96213062060997, 0.446768212364987, 0.77353213634342, 
0.548623297130689, 2.2196321694646, 1.45420034159906, 3.50267172069289, 
2.07647292385809, 5.17379751102999, 5.37321635615081, 0.536520478781313, 
4.249543545302, 2.88072110014036, 5.09331024787389, 5.28932340652682, 
4.84812613157555, 2.38863884215243, 3.12176107242703, 4.53757327166386, 
4.98468712042086, 4.52686174446717, 1.80437495210208, 3.48324069567025, 
5.70025397161953, 1.30593974888325, 2.18962532537989, 4.7624047647696, 
6.54404626064934, 6.3754019739572, 5.28995988494717, 2.22903218166903, 
0.464576691854745, 5.20725148450583, 6.59460727567784, 0.79798748344183, 
4.37215717323124, 5.55034466832876, 0.259810805087909, 5.4682707269676, 
3.71384913474321, 5.51100698136725, 2.77795236581005, 1.05121230264194, 
0.904357444494963, 3.18293640762568, 2.48499805224128, 3.32985564181581, 
2.38327998109162, 3.36443712748587, 6.46839950582944, 4.34225206868723, 
6.94606997421943, 0.134431336307898, 1.0681464811787, 4.21864536381327, 
3.86801736662164, 0.557952718809247, 3.40971007733606, 0.395286374958232, 
5.5910315613728, 4.15412816079333, 3.24207481532358, 2.41977618425153, 
4.38203789270483, 6.15722388075665, 5.72545193554834, 0.837054459843785, 
5.09624301758595, 4.24583781324327, 5.51288957195356, 3.98278430965729, 
6.61949961679056, 5.5619070858229, 5.38388560921885, 2.72296543628909, 
2.2259249468334, 2.12436940404586, 4.55318662081845, 3.49066230864264, 
5.46803683880717, 5.13995757466182, 4.33128586504608, 5.65111118694767, 
1.81098679662682, 5.90350646642037, 6.9880753676407, 3.31754910969175, 
1.42874774034135, 2.5919971477706, 4.36564357718453, 4.14156896178611, 
0.907076398842037, 5.03209447534755, 3.50394161348231, 5.01333990646526, 
2.4395019270014, 4.00608126609586, 3.85247602593154, 1.92078053019941, 
5.22815201384947, 6.2540827235207, 3.57969641359523, 5.42042342806235, 
0.922570331487805, 2.14553649444133, 6.26563199656084, 0.584600244648755, 
4.09478736598976, 3.61869611288421, 5.61629920639098, 3.61910280701704, 
6.5431126980111, 1.45589658245444, 4.61781946895644, 1.41395127214491, 
0.424649354303256, 2.20764554711059, 2.32424536324106, 3.0085478592664, 
3.31426100130193, 2.18899470940232, 4.01463987026364, 6.17637578048743, 
2.71333927591331, 5.7106029172428, 1.98646189505234, 0.667557667708024, 
3.07633737288415, 3.09047992853448, 5.30754509777762, 1.70720728719607, 
4.50194623717107, 4.98590464075096, 4.94538911292329, 0.528201168868691, 
3.39843238191679, 3.4805209916085, 1.12188241397962, 0.60105063719675, 
6.7118163947016, 6.55771014792845, 6.65756058366969, 3.0354921205435, 
4.55017648707144, 2.5476835295558, 5.63207563967444, 3.93135939515196, 
3.55730180884711, 4.4150811561849, 2.66077705891803, 6.30368497897871, 
6.99334880686365, 0.253469441318884, 6.60101639898494, 6.27822431339882, 
5.96356187784113, 0.272476761834696, 5.55220138723962, 5.9418785860762, 
4.07551913661882, 1.1400810580235, 0.835778421023861, 0.207219482865185, 
2.39975797780789, 5.21510744141415, 6.51855618343689, 1.18180589354597, 
0.767605187138543, 2.5686160994228, 2.54523882735521, 3.73794352193363, 
4.78204908687621, 4.62337116152048, 4.81178568978794, 0.388412959873676, 
0.0411090981215239, 1.8118692303542, 6.79648471879773, 3.47989189950749, 
2.32970578130335, 6.99839020613581, 4.10990862525068, 4.43040328519419, 
1.25007290858775, 0.504601462977007, 1.35509265796281, 5.6739231008105, 
4.46856182743795, 4.43292348692194, 1.7337932663504, 2.34387436020188, 
6.20670560165308, 5.21738122170791, 4.31457831710577, 6.94854912417941, 
0.915300794877112, 3.68428604514338, 6.33835580619052, 3.86307967407629, 
5.50000065658242, 3.57583113899454, 4.45316662243567, 0.396047094138339, 
4.59239823347889, 0.712187129305676, 6.48146787029691, 0.790960676735267, 
1.13155325083062, 3.6196393892169, 2.44487521681003, 5.90808478486724, 
0.172094851732254, 4.12020624312572, 0.193159742979333, 2.27302405494265, 
4.7721633198671, 2.79867990990169, 1.67313155089505, 6.66059030778706, 
0.835861994652078, 5.23712413292378, 5.70345002482645, 3.81919791433029, 
0.717844031285495, 4.62532560247928, 4.56782407616265, 6.43218668666668, 
4.01907785679214, 3.4781309729442, 6.60032802727073, 3.25162809854373, 
1.00224118796177, 5.28598691383377, 5.79524349537678, 1.88583829812706, 
5.23439469723962, 2.08149957004935, 0.172328498680145, 3.46160246175714, 
6.8778549192939, 2.20208570547402, 2.21094923163764, 4.19191446970217, 
6.79140090686269, 1.7596512301825, 0.331691211787984, 3.71819271915592, 
4.12324235937558, 3.03292068070732, 3.14397358288988, 6.41280459193513, 
0.325597110437229, 2.78717174078338, 3.78346392000094, 2.15289128012955, 
1.91871184087358, 0.166334042558447, 3.40869065118022, 0.164784359512851, 
4.81063592084683, 5.59261277318001, 3.20621390570886, 5.3196173212491, 
0.997261012671515, 5.06095262453891, 6.46167174889706, 5.82082040421665, 
6.44449155800976, 1.49811770953238, 0.0192595163825899, 2.2283662231639, 
4.79183263680898, 5.07450013002381, 1.87455640593544, 0.64247514680028, 
2.73048335011117, 3.13952887500636, 5.17273314599879, 2.57577190105803, 
6.34411540278234, 2.07800803962164, 0.778125731041655, 1.29991004150361, 
0.954306103987619, 6.23654383490793, 0.480485521489754, 1.81091342400759, 
2.59092439897358, 2.19786719139665, 2.47539811395109, 5.69216986838728, 
2.60561196622439, 2.72568021994084, 5.73809769237414, 5.28804755024612, 
3.17954868660308, 0.505570620764047, 0.896342191146687, 4.81725191487931, 
0.20131106628105, 0.692817791132256, 1.93813877669163, 2.28227129159495, 
1.38975778897293, 2.62904909159988, 6.7453944508452, 0.815447821514681, 
3.56666115880944, 1.45562997087836, 4.39345230837353, 1.94914716482162, 
6.34848006884567, 2.43539050477557, 4.69220185605809, 6.77832867321558, 
5.00803724466823, 1.6455108448863, 0.900199559517205, 3.88902160758153, 
6.7704666305799, 5.70777405961417, 6.88831905042753, 6.96521803247742, 
4.08059633965604, 2.96147064934485, 0.47023283271119, 1.32748077088036, 
1.42374711087905, 4.15759756648913, 4.20845754328184, 4.50638034474105, 
5.72494196821935, 6.19907499593683, 2.88488351437263, 6.83081391081214, 
3.64464653120376, 1.75822671200149, 0.455752308946103, 1.70355808851309, 
0.39064734429121, 2.48014936875552, 5.49560521147214, 5.83223332860507, 
0.139375271042809, 1.14092703443021, 3.45735920220613, 2.0369054232724, 
0.813209735788405, 5.03688533953391, 5.82378641236573, 5.41805751109496, 
4.13369493186474, 3.8005820622202, 3.88000204134732, 2.62377274315804, 
4.61035502282903, 5.28748917253688, 1.8393365398515, 5.61172570241615, 
2.68849984998815, 0.786816984182224, 2.61302443430759, 4.58396751107648, 
3.49712035572156, 1.82683911407366, 3.77825222956017, 2.57311869016849, 
6.31698969588615, 2.58390279300511, 6.51086786924861, 5.61838922020979, 
6.16136846318841, 3.60698981536552, 3.96247277734801, 6.72405482339673, 
1.99734802101739, 0.30031424947083, 2.0189898062963, 2.93271886347793, 
3.46915056952275, 4.2390601253137, 5.84646597877145, 3.83646500040777, 
2.31444999552332, 0.188318768516183, 2.85518174711615, 5.25288511882536, 
0.956734268460423, 2.03814007132314, 3.96439500013366, 0.748275059042498, 
2.04524141270667, 0.831118391826749, 5.42289266875014, 4.72776467096992, 
4.91202931664884, 6.24671443970874, 0.40743977134116, 4.9216043415945, 
6.61033717123792, 2.69864852074534, 3.67311166855507, 1.10293509834446, 
3.60772403213196, 2.73445329465903, 1.86697288719006, 5.0545593642164, 
2.395973442588, 2.8370767228771, 5.05784078058787, 4.87398787494749, 
5.75733723049052, 0.31468792911619, 0.0810647895559669, 6.99554428597912, 
1.95557675370947, 0.901982843875885, 2.94414106803015, 5.96128946822137, 
2.65498240664601, 0.217784639680758, 2.14479523361661, 2.55597622133791, 
4.19081571884453, 4.86338929878548, 4.58711919584312, 3.29114589630626, 
6.6746605860535, 1.97876466740854, 4.08325864817016, 1.07040398614481, 
3.21018120017834, 5.30659376038238, 5.36815215577371, 0.00245642871595919, 
0.0691241638269275, 6.68297754088417, 1.58652311027981, 6.30234997835942, 
3.62163636670448, 3.22776469192468, 4.5155286793597, 6.75800520414487, 
3.88895645248704, 3.54020084650256, 1.44966803281568, 2.09709535632282, 
4.81882090959698, 1.15948950685561, 6.04225403722376, 2.963695530314, 
6.38058017008007, 5.80751768220216, 1.71611109911464, 2.79099478363059, 
2.41889961133711, 2.32556171552278, 0.0883512925356627, 6.9995247379411, 
3.84287614305504, 4.00286772171967, 4.42158935265616, 1.400477448944, 
2.39856753847562, 5.90414739912376, 3.03577814646997, 0.0110342614352703, 
0.168836373370141, 1.41425726818852, 4.00271105905995, 4.98599336459301, 
1.89536201977171, 3.9283338743262, 0.614770440151915, 1.73598027857952, 
5.41714202798903, 1.46022334555164, 3.79370965436101, 3.12699181213975, 
3.59238314721733, 4.65249584731646, 3.32185244420543, 5.26871391478926, 
4.15930192708038, 6.7973371068947, 0.313007909804583, 3.19235163577832, 
2.97261857078411, 1.73676382820122, 4.66682833177038, 4.6860879198648, 
4.03018201445229, 3.10263388720341, 1.32552696228959, 5.95434060739353, 
2.62647217395715, 4.80216821469367, 5.63121176953427, 1.41636495082639, 
6.85768754570745, 2.68580284598283, 4.31594003201462, 1.0302362118382, 
6.26712256623432, 1.11002736329101, 5.28058405430056, 4.37487043137662, 
0.527325612958521, 4.25265334220603, 3.70193625497632, 5.76612052903511, 
1.57872382528149, 0.696659211767837, 6.75427101878449, 6.16577791981399, 
6.66213104804046, 3.29253815882839, 3.42726589157246, 4.0177620081231, 
6.71022335370071, 3.15187553153373, 1.51413801684976, 4.04758316092193, 
5.97136607184075, 0.926300210878253, 0.217437800485641, 5.44836337561719, 
1.0358884492889, 3.19548146799207, 0.484532476402819, 5.3735640461091, 
4.27300057560205, 5.31614892114885, 4.72617712733336, 6.95729128620587, 
6.39377269055694, 6.44958384498022, 6.70900673628785, 6.41723836702295, 
5.91136061097495, 3.3423468710389, 0.798795204842463, 6.33571439352818, 
2.16188409295864, 5.5525766715873, 0.724902585148811, 4.01812910102308, 
4.54836841649376, 4.17949470784515, 0.88475192990154, 2.20334027148783, 
1.59861557115801, 0.24661932932213, 2.1714241518639, 5.10775746637955, 
6.79656764864922, 4.73339378950186, 1.97431626310572, 5.73110237857327, 
5.97078674612567, 6.0667193995323, 5.82251167250797, 5.86500261374749, 
2.14975096983835, 2.84774531424046, 4.78922765539028, 2.04362053610384, 
5.73145949537866, 2.45116844074801, 0.2935463974718, 4.08884599781595, 
6.13042048923671, 2.75879301293753, 1.75654948619194, 2.9111724907998, 
0.433084113756195, 2.81707684043795, 0.703652605647221, 4.62322162440978, 
4.28534257900901, 1.7281222990714, 4.21868609450758, 4.33313153381459, 
0.496840649750084, 3.84199115703814, 5.83597016241401, 2.12629948253743, 
3.98680891329423, 4.92703744559549, 4.53629354131408, 3.26493959221989, 
4.0471952536609, 4.09169854968786, 4.23641212820075, 0.430894190678373, 
2.01200605276972, 5.40868371119723, 3.65091525414027, 3.9592286364641, 
5.83374688681215, 1.3859362390358, 5.84397498494945, 1.16547449212521, 
3.0411508413963, 4.43414744664915, 0.260074241785333, 6.62293692328967, 
5.41268742713146, 2.67649116972461, 0.910400537541136, 6.56120144040324, 
1.61332928063348, 2.39461743202992, 2.30256121745333, 4.20186537550762, 
2.77619664487429, 0.163277477025986, 4.94368034042418, 6.65968558308668, 
1.76053233887069, 5.47516668075696, 3.04788401257247, 1.41723344963975, 
2.71785448142327, 1.42279405728914, 2.55776387033984, 2.12434200034477, 
1.68730971636251, 3.72791926632635, 6.66749073704705, 2.68043287936598, 
2.52690523955971, 1.97245820611715, 3.1319943794515, 4.39257474779151, 
5.5203092454467, 3.4128778304439, 3.15206111362204, 6.93686083774082, 
0.933865265455097, 1.40841703000478, 6.62593134562485, 4.50891529466026, 
3.68356430134736, 0.421411387156695, 2.16128659481183, 0.348314602626488, 
6.33539775805548, 5.35741244908422, 2.69869966595434, 2.53163740108721, 
2.56699647614732, 6.05175887420774, 1.43215362727642, 5.53229719283991, 
1.86178226047195, 1.99612038442865, 1.33980036433786, 4.9547353705857, 
1.90330843464471, 0.726320235291496, 2.93935337546282, 2.54052775725722, 
1.45150278508663, 3.48946674517356, 1.01745510054752, 5.25755288638175, 
4.11572004342452, 1.7962098014541, 6.83898255904205, 4.04192714067176, 
1.64694803161547, 1.31532435445115, 0.0506307873874903, 4.22531003714539, 
0.465796819888055, 3.31896112067625, 4.58086669933982, 5.04752894747071, 
2.95058066071942, 4.09402674622834, 1.92380371224135, 0.779918553074822, 
0.0901559730991721, 6.13424473977648, 0.631241590017453, 4.37788666551933
)

ggplot(enframe(x), aes(value)) + geom_histogram(bins = 10) + theme_minimal()




### Question 3.a (2 point)

Find the **methods of moments** estimator of $\theta$ using the sample $X_1, X_2, \ldots, X_n$.


We start by computing the first moment of $X$:

$$E(X) = \int_0^\theta \frac{x}{\theta} \, dx = \left. \frac{x^2}{2\theta} \right|_{x = 0}^\theta = \frac{\theta}{2}$$

Then solve $E(X) = \theta/2$ for $\theta$, to get $\theta = 2 E(X)$. Substituting $\bar X$ for $E(X)$, $\hat \theta = 2 \bar X$.

{r}


### Question 3.b (2 point)



For a given $\theta$ value, implement the **likelihood function**:
{r}
likelihood <- function(theta) {
  ifelse(theta >= max(x),
  (1/theta)^length(x),
  0)
}


{r}
x <- runif(1000, min = 0, max = 1)
likelihood <- function(theta) {
  ifelse(theta >= max(x),
  (1/theta)^length(x),
  0) 
}


Plot the likelihood for $\theta \in [0, 20]$:
{r}
## the "x" below is actually our theta parameter
## the curve function is a special function that needs an expression involving "x"
## The "Vectorize" function allows us to take many theta values simultaneously
curve(Vectorize(likelihood)(x), from = 0, to  = 20)


What do you notice? Where is the highest point of the plot?

{r}


### Part (c) (2 pt)

Find the **maximum likelihood estimator** for $\theta$ as a function of the data. Compute the MLE estimate from x given in at the start of the problem. Compare it to your graph. Do the two solutions agree?
{r}


## Question 4 (5 points)

Consider the Poisson distribution with probability mass function:

$$p(x) = \frac{e^{-\lambda} \lambda^x}{x!}$$
for $\lambda > 0$.

The Poisson distribution has four related functions in R which we can use:

* dpois: the probability mass function
* ppois: the cumulative distribution function
* qpois: the quantile function (inverse cdf)
* rpois: generate random deviates (random numbers that follow this distribution)

### Question 4.a (1 point)

{r}
lambda <- 3
x <- data.frame(x = 0:10)


Using the mutate function, add 2 new columns to the data frame x:

* d: The PMF evaluated at each x value.
* p: The CDF evaluated at each x value.

Graph the PMF and CDF for the Poisson distribution with $\lambda = 3$ using the data frame x. The geom_col will be helpful for the PMF. The geom_step function is useful for the CDF.

{r}
x <- x %>% 
  mutate(
    d = dpois(x, lambda),
    p = ppois(x, lambda)
  )

ggplot(x, aes(x = x, y = d)) + 
  geom_col(fill = "blue") +
  labs(
    title = "Poisson PMF with Lambda = 3",
    x = "x",
    y = "PMF"
  ) 

ggplot(x, aes(x = x, y = p)) +
  geom_step() + 
  labs(title = "Poisson CDF with Lambda = 3",
       x = "x",
       y = "CDF"
  )



### Question 4.b (2 points)


Suppose that we have observed $N$ events in a fixed interval of time. The time between events is distributed as an exponential distribution with rate parameter $\lambda$:

$$f(x) = \lambda e^{-\lambda x}$$

for $x > 0$ and as before $\lambda > 0$. Notice that $N$ is a random variable, in particular a Poisson distributed random variable.

Suppose that we want to test a hypothesis about $\lambda$. It would be natural to use the total number of observed events as a test statistic. 

If our null hypothesis is that $\lambda = 3$ and our alternative is that $\lambda = 4$, graph both the null and alternative distributions of the test statistic. Looking at the plot, where would be a good place to locate an interval of the form $[a, \infty)$ or $[0, a]$, such that this interval would have good power?

{r}
lambda_alt <- 4
x_alt <- data.frame(x = 0:10)

x_alt <- x_alt %>% 
  mutate(
    d = dpois(x, lambda_alt),
    p = ppois(x, lambda_alt)
  )

ggplot(x_alt, aes(x = x, y = d)) +
  geom_col(fill = "red") + 
  labs(title = "Poisson PMF with Lambda = 4",
       x = "x",
       y = "PMF"
  )

ggplot(x_alt, aes(x = x, y = p)) +
  geom_step() + 
  labs(title = "Poisson CDF with Lambda = 4",
       x = "x",
       y = "PMF"
  )

ggplot() + 
  geom_col(data = x, aes(x = x, y = d), fill = "blue", alpha = 0.5) +
  geom_col(data = x_alt, aes(x = x, y = d), fill = "red", alpha = 0.5) +
  labs(
    title = "Poisson PMF with Lambda = 3 (Blue) and Lambda = 4 (Red)",
    x = "x",
    y = "PMF"
  )

ggplot() + 
  geom_step(data = x, aes(x = x, y = p), color = "blue", alpha = 0.5) +
  geom_step(data = x_alt, aes(x = x, y = p), color = "red", alpha = 0.5) +
  labs(
    title = "Poisson CDF with Lambda = 3 (Blue) and Lambda = 4 (Red)",
    x = "x",
    y = "CDF"
  )


### Question 4.c (1 point)

Using qpois find the interval $[a, \infty)$ or $[0, a]$ that would have a significance level of 0.05 with the most power for the null hypothesis $\lambda = 3$ against the alternative that $\lambda = 4$.

{r}
lambda_null <- 3
alpha <- 0.05

crit_val <- qpois(1 - alpha, lambda_null)
crit_val

lambda_alt <- 4
power <- 1 - ppois(crit_val - 1, lambda_alt)
power

crit_val_left <- qpois(alpha, lambda_null)
crit_val_left

power_left <- ppois(crit_val_left, lambda_alt)
power_left


### Question 4.c (1 point)

{r}
# the next line guarantees that the random numbers we generate will always be the same.
set.seed(406406406)
y <- rpois(1, lambda = 3)


Suppose we observe that $Y = r y$. Using the interval you found in the previous part, test the null hypothesis $\lambda = 3$ against the alternative that $\lambda = 4$. What is your conclusion?

{r}
crit_val <- 6
if(y >= crit_val) {
  result <- "Reject the null hypothesis"
} else {
  result <- "Fail to reject the null hypothesis"
}

y
result
